### ISSUE TITLE
Apply basic configurations to the VPS

### ISSUE THREAD

**Issue by iraida07** [callback-demons/callback-news-api#26]
- [x]  Create user and groups
- [x]  Set permissions
- [x]  Set app ports (ssh 22)
- [x]  Set the firewall rules

Deliverable → https://www.notion.so/iraida07/Infraestructure-configuration-a4bc4f177d7f4a79b2e017e0655afbc5

**Comment by GerardoMarquezC** [comment]
Se agregan configuraciones de DNS y firewall

![image](https://user-images.githubusercontent.com/40473845/82720531-132ed180-9c7a-11ea-8f6b-da58b272c39c.png)

![image](https://user-images.githubusercontent.com/40473845/82720545-2641a180-9c7a-11ea-98b8-98b7d4d3601c.png)

![image](https://user-images.githubusercontent.com/40473845/82720573-4ffac880-9c7a-11ea-93b4-e9237c953160.png)
